# Generated by Django 5.2.13 on 2026-04-18 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.CharField(choices=[('1', 'Comptes de capitaux'), ('2', "Comptes d'immobilisations"), ('3', 'Comptes de stocks'), ('4', 'Comptes de tiers'), ('5', 'Comptes financiers'), ('6', 'Comptes de charges'), ('7', 'Comptes de produits')], max_length=1)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ACH', 'Achats'), ('VTE', 'Ventes'), ('BQ', 'Banque'), ('CAI', 'Caisse'), ('OD', 'Opérations diverses'), ('AN', 'A nouveaux')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('numero_piece', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manuel', help_text='manuel | api_bancaire | import_fec | qonto | pennylane', max_length=50)),
                ('valide', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='app_compta.journal')),
            ],
            options={
                'ordering': ['-date_ecriture', '-id'],
                'unique_together': {('journal', 'numero_piece')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('montant_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('lettrage', models.CharField(blank=True, help_text='Code de lettrage pour rapprochement tiers', max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='app_compta.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app_compta.ecriturecomptable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_externe', models.CharField(max_length=100, unique=True)),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField()),
                ('libelle_banque', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('statut', models.CharField(choices=[('brut', 'Importée — non traitée'), ('imputee', 'Imputée comptablement'), ('ignoree', 'Ignorée')], default='brut', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('ecriture_generee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_source', to='app_compta.ecriturecomptable')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
    ]
